### ISSUE TITLE
Running in docker - HTML formating

### ISSUE THREAD

**Issue by markiceman** [geluk/matrix-webhook-gateway#19]
I have running wegnook-gateway in docker. All works, but HTML formating no. If I try:

`curl -k -X POST -H 'Content-type: application/json' --data '{"text":"<b>Hello world !</b>","format":"html"}' URL`

Then I have message:

`<b>Hello world !</b>`

Is it some issue with HTML formating?

It was working in older webhook bridge from turt2live.

**Comment by geluk** [comment]
You're right, I had most of the functionality already in place to support this, but the application was missing a few checks.
I've updated the application to support this, which you can test by tracking the `:dev` tag on Docker and making sure you're up to date (`docker pull geluk/matrix-webhook-gateway:dev`).

**Comment by geluk** [comment]
Fixed in version 1.1.

**Comment by markiceman** [comment]
Thank You.

I trying it with latest version of docker, but still not works.

**Comment by geluk** [comment]
Thanks for your report! I looked into it further, and found out that the plaintext content wasn't set correctly yet. I've fixed it and tested it, and it seems to be working now. You can test it by fetching the `:dev` tag on Docker.
